### ISSUE TITLE
Local geração arquivo?

### ISSUE THREAD

**Issue by eliandrocardoso** [totvs/tlpp-sample-rest-documentation#1]
Olá, em qual pasta o arquivo será gerado?

**Comment by JoseEgidioGJunior** [comment]
Olá

Primeiramente agradecemos o seu interesse e pedimos desculpas. 
Peço que considere a retificação abaixo:

Utilizando a funcionalidade **tlpp.doc.generate()** por execução via linha de comando ou via SmartClient, será gerado um arquivo **.YAML** no  **root** da sua aplicação contendo a documentação.
Sobre a visualização da documentação, esta funcionalidade estará disponível a partir da versão 20.3.2.0 do appserver, utilizando a nossa interface web GUI, a partir das configurações **APP_MONITOR** feitas no arquivo _appserver.ini_
Publicaremos mais detalhes a respeito em breve, mas caso queira dar uma olhada na documentação oficial a respeito da interface web GUI e demais produtos do **TLPPCore**, acesse esse link: https://tdn.totvs.com/display/tec/GUI

Atenciosamente 
TLPPCore Team.

**Comment by denardi-totvs** [comment]
Olá @eliandrocardoso,
Tudo bem?

Sua dúvida foi sanada?
Precisa de mais algum apoio?

Att,
Denardi - Dev TLPPcore team
