### ISSUE TITLE
Includes x Documentação

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tlpp-sample-rest-documentation#2]
Bom dia pessoal,
tudo bem?

Essa documentação está muito cru mesmo sendo para dev totvs especialista.

O jeito que estão montando não fala como referência um fonte TLPP REST e de como gerar a documentação na saída.

Muitos exemplos que não condiz como informado, includes não existe como "tlpp-i18n.th" mesmo baixando o tlpp.rpo da documentação está tem esse include que se torna principal na geração da documentação. 

Estamos precisando dessa melhoria urgentemente para exportar nossas API direto para SWAGGER.

Att;

Michael Castro

**Comment by denardi-totvs** [comment]
Olá Michael,
Tudo bem?

Qual versão do tlppCore e do AppServer (binário) você está utilizando?

Caso vc tenha REST configurado em seu ambiente, basta acessar o endpoint: /totvs/environment

Porém, caso não queira subir um REST, execute o código abaixo:

```
cVersion += '{"tlpp": [ '                            +; 
	tlpp.environment.getVersion(0,.T.)          + ','  +;
	tlpp.environment.getVersionName(.T.)        + ','  +;
	tlpp.environment.getSourceRevision(.T.)     + ','  +;
	tlpp.environment.getSourceRevisionDate(.T.)
cVersion += '],'
cVersion += '"appserver":['                              +; 
	tlpp.environment.getAppServerVersion(.T.)       + ','  +;
	tlpp.environment.getAppServerVersionName(.T.)   + ','  +;
	tlpp.environment.getAppServerRevision(.T.)      + ','  +;
	tlpp.environment.getAppServerVdrRevision(.T.)   + ','  +;
	tlpp.environment.getAppServerBuildDate(.T.)     + ','  +;
	tlpp.environment.getAppServerBuildTime(.T.)
cVersion += ']}'
conout(cVersion)
```

Assim que obter as versões, me passe que eu analisarei porque não está extraindo a include do i18n e iremos lhe auxiliar nesse processo.

A documentação ainda é inicial pois trata-se de um recurso novo, porém estamos trabalhando para criar mais exemplos e como utilizá-los.
De qualquer forma, pedimos desculpas pelo inconveniente.

Outro ponto, é que pode-se utilizar o REST-DOC sem utilizar a tradução de strings, gerando a documentação somente para 1 (um) idioma.
Veja o exemplo: https://github.com/totvs/tlpp-sample-rest-documentation/blob/main/src/rest/basic/sample_02_basic_by_annotation.tlpp
Nesse caso, você não precisa utilizar a tlpp-i18n.th

Sinta-se à vontade de postar suas dúvidas aqui, pois iremos ajudar.

No aguardo das versões de seu ambiente.

Att,
Denardi - Dev TLPPcore team

**Comment by maximinocastro** [comment]
Boa tarde @denardi-totvs, 

Segue as informações solicitadas;

{"tlpp": [ {"version":"01.03.02"},{"majorVersion":"01"},{"minorVersion":"03"},{"patchVersion":"02"},{"versionNumber":10302},{"majorVersionNumber":1},{"minorVersionNumber":3},{"patchVersionNumber":2},{"versionName":"TLPP HARPIA"},{"sourceRevision":"3bf82b787f021411d42f1575227f2b4439adb3c0"},{"sourceRevisionDate":"2022/10/01 14:49:37"}],"appserver": [ {"version":"20.3.1.0"},{"versionName":"HARPIA"},{"revision":"36666"},{"vdrRevision":"3087"},{"buildDate":"Oct  5 2022"},{"buildTime":"03:12:23"}] }

Ah eu tentei utilizar esse REST-DOC quando copia e cola fica apresentando erro e não compilar. E não entendi muito bem, será que não conseguirmos marcar um call 15min só para me explicar esse processo de exportação para o SWAGGER ?

Att;

Michael Castro

**Comment by denardi-totvs** [comment]
Olá @maximinocastro,

Você está utilizando uma versão de tlppCore que não está disponível esse recurso, por isso você não conseguiu extrair as includes necessárias e nem compilar os fontes.

O motor de geração de DOC Swagger está disponível a partir de: tlppCore 01.04.02 + AppServer 20.3.1.10
Por favor, atualize seu ambiente com uma versão superior ou igual à acima.

Infelizmente, sem essa atualização você não conseguirá nem compilar os fontes.

No aguardo de seu feedback.

Abs,
Denardi - Dev TLPPcore team

**Comment by maximinocastro** [comment]
Olá @denardi-totvs,

Ah agora faz sentido não estar extraindo e nem gerando a doc.

Perfeito, vou fazer a atualização e tentar novamente.

Att.

Michael Castro

**Comment by denardi-totvs** [comment]
Bom dia @maximinocastro,

Ok, espero você atualizar e me passar o feedback.

Manterei por enquanto essa Issue aberta para mantermos contato, ok?

Abs,
Denardi - Dev TLPPcore team

**Comment by maximinocastro** [comment]
Perfeito.

**Comment by maximinocastro** [comment]
@denardi-totvs boa noite,

acabei de atualizar meu ambiente para o ultimo pacote disponibilizado no portal da TOTVS.

![image](https://github.com/totvs/tlpp-sample-rest-documentation/assets/42280023/10691883-9609-492c-8ebe-5c2836ce31d0)

E não trouxe os includes conforme informado.

Att.

**Comment by denardi-totvs** [comment]
Oi @maximinocastro,
Tudo bem?

A versão do AppServer 20.3.1.0 possui a versão do tlppCore 01.03.02, ainda é inferior à versão de que você precisa para obter acesso a este módulo.

Por favor, utilize os links abaixo para obter as versões mais atualizadas:
20.3.1.12 - Linux: https://suporte.totvs.com/portal/p/10098/download?e=1118847
20.3.1.12 - Windows: https://suporte.totvs.com/portal/p/10098/download?e=1118837

Abs,
Denardi - Dev TLPPcore team

**Comment by maximinocastro** [comment]
@denardi-totvs perfeito,

vou realizar o download e fazer os testes.

Att;

Michael Castro

**Comment by denardi-totvs** [comment]
@maximinocastro 

Ok, no aguardo!

Manterei por enquanto essa Issue aberta para mantermos contato, ok?

Abs,
Denardi - Dev TLPPcore team

**Comment by denardi-totvs** [comment]
Olá @maximinocastro,
Boa noite!

Conseguiu atualizar seu ambiente?

Abs,
Denardi - Dev TLPPcore team

**Comment by maximinocastro** [comment]
Bom dia @denardi-totvs 
tudo bem?

Consegui sim, porém agora não tô entendendo como eu faço para gerar o arquivo baseado na minha API, tá um pouco confuso.

Se puder me ajudar agradeço.

Att;

Michael Castro

**Comment by denardi-totvs** [comment]
Bom dia @maximinocastro,

Bom, vamos à prática agora :-)

Deixa eu tentar entender em que pé está seu desenvolvimento da documentação:

Você já?
1 - Criou uma API com annotation? 
2 - Informou o Description?
3 - Quais mais dados foram informados?
4 - Você optou por documentar diretamente na Annotation? pelo ID? ou por uma function?
5 - Já fez a documentação mas só não está conseguindo gerar o arquivo final?

Abs,
Denardi - Dev TLPPcore team

**Comment by eduardobrust** [comment]
Boa Noite.
Me interessei pelo projeto.
Tenho uma API - CRUD e fiz em tlpp com annotation e informei o description.
Tenho um rest 2.0 configurado e tb um rest tlpp.
Minha dúvida é : onde executo este comando ? tlpp.doc.generate( 'swagger', 'api_doc', {8080} ) ? em que local ?
Não ficou claro esta parte pra mim.
