### ISSUE TITLE
Comando de geração de documentação.

### ISSUE THREAD

**Issue by eduardobrust** [totvs/tlpp-sample-rest-documentation#3]
Boa Noite.
Me interessei pelo projeto.
Tenho uma API - CRUD e fiz em tlpp com annotation e informei o description.
Tenho um rest 2.0 configurado e tb um rest tlpp.
Estou na release 12.1.2310 do protheus atualizada.
Minha dúvida é : onde executo este comando ? tlpp.doc.generate( 'swagger', 'api_doc', {8080} ) ? em que local ?
Não ficou claro esta parte pra mim.

**Comment by denardi-totvs** [comment]
Olá @eduardobrust,
Bom dia! tudo bem?

A função tlpp.doc.generate() ainda não é uma Main Function, portanto ela não pode ser executada diretamente pelo VSCode ou por linha de comando.

Portanto, você precisa encapsular a chamada em uma função sua, algo como:

User Function MyGenDoc()
  tlpp.doc.generate( 'swagger', 'api_doc', {8080} )
return Nil

Reforçando os parâmetros:
- cFormat: utilizar por enquanto sempre 'swagger';
- nNameFile: String com o nome do documento que será gerado;
- aPorts: Array com as portas REST que deseja gerar a documentação.

Um ponto importante para ressaltar:

Para APIs REST tlppCore que utilizam annotation você utilizará o description para registrar sua documentação.

Para APIs do REST 2.0 que ainda utilizam a classe WsRestFul, será preciso utilizar um outro modo para registrar a documentação, portanto ainda será lançado em releases novos.

Abs,
Denardi - Dev TLPPcore team
